import type {
  User,
  Lead,
  Visit,
  Product,
  Enquiry,
  Quotation,
  Demo,
  ServiceRequest,
  Activity,
  Company,
  ItemService,
  Task,
  Tenant, // Added Tenant type
} from "./types"

import { defaultLeadStatuses, defaultAssignmentRules } from "./workflow-config"

// Re-export workflow configuration for use in data-store
export { defaultLeadStatuses, defaultAssignmentRules }

// Mock Users
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@nexflow.com",
    role: "Sales Manager",
    phone: "+91 98765 43210",
    territory: "North India",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya.sharma@nexflow.com",
    role: "Sales Executive",
    phone: "+91 98765 43211",
    territory: "Delhi NCR",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "u3",
    name: "Amit Patel",
    email: "amit.patel@nexflow.com",
    role: "Service Manager",
    phone: "+91 98765 43212",
    territory: "West India",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "u4",
    name: "Sneha Reddy",
    email: "sneha.reddy@nexflow.com",
    role: "Customer Care Executive",
    phone: "+91 98765 43213",
    territory: "South India",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "u5",
    name: "Vikram Singh",
    email: "vikram.singh@nexflow.com",
    role: "Field Executive",
    phone: "+91 98765 43214",
    territory: "Mumbai",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "u6",
    name: "Kavita Desai",
    email: "kavita.desai@nexflow.com",
    role: "Functional Team",
    phone: "+91 98765 43215",
    createdAt: new Date("2024-01-01"),
  },
]

// Mock Products (from your spreadsheet)
export const mockProducts: Product[] = [
  {
    id: "p1",
    modelName: "NObreath FeNO",
    manufacturer: "Bedfont Scientific",
    country: "United Kingdom",
    category: "Pulmonology",
    subCategory: "Breath Analyzers",
    productType: "Portable FeNO",
    description: "FeNO with Standard Accessories",
    standardPriceRange: "21000 - 24000",
    priceA: 21000,
    priceB: 24000,
    priceC: 18000,
    priceD: 15000,
    priceE: 14000,
    buyBackPrice: 11000,
  },
  {
    id: "p2",
    modelName: "SmartPFT USB",
    manufacturer: "Medical Equipment Europe",
    country: "Germany",
    category: "Pulmonology",
    subCategory: "Spirometer",
    productType: "PC Based Spirometer",
    description: "PC Based Spirometer",
    standardPriceRange: "12000 - 14000",
    priceA: 12000,
    priceB: 14000,
    priceC: 10000,
    priceD: 9000,
    priceE: 8500,
    buyBackPrice: 8000,
  },
  {
    id: "p3",
    modelName: "CustoCardio BT",
    manufacturer: "Customed",
    country: "Germany",
    category: "Cardiology",
    subCategory: "Digital ECG",
    productType: "PC Based ECG Machine",
    description: "Digital ECG Machine with Bluetooth",
    standardPriceRange: "21000 - 30000",
    priceA: 21000,
    priceB: 30000,
    priceC: 25000,
    priceD: 22000,
    priceE: 20000,
    buyBackPrice: 15000,
  },
  {
    id: "p4",
    modelName: "CustoCardio",
    manufacturer: "Customed",
    country: "Germany",
    category: "Cardiology",
    subCategory: "Digital ECG",
    productType: "PC Based ECG Machine",
    description: "Digital ECG Machine with USB Only",
    standardPriceRange: "18000 - 25000",
    priceA: 18000,
    priceB: 25000,
    priceC: 20000,
    priceD: 18000,
    priceE: 16000,
    buyBackPrice: 12000,
  },
]

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: "LD-2024-0001",
    firstName: "Sanjay",
    lastName: "Gupta",
    leadName: "Dr. Sanjay Gupta",
    email: "sanjay.gupta@apollo.com",
    phone: "+91 98765 11111",
    alternatePhone: "+91 11 2692 5858",
    companyName: "Apollo Hospitals",
    industry: "Healthcare - Multi-specialty Hospital",
    website: "www.apollohospitals.com",
    address: "Indraprastha Apollo Hospital, Sarita Vihar",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110076",
    status: "Quotation Sent",
    source: "Website Inquiry",
    leadType: "Hot",
    leadScore: 85,
    preferredContactMethod: "Email",
    nextFollowUpDate: new Date("2024-12-22"),
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    interestedProducts: ["is1", "is2"],
    employeeCount: "5000+",
    annualRevenue: "₹500Cr+",
    notes: "Interested in pulmonology equipment for new cardiac care unit. Budget approved. Decision maker confirmed.",
    createdBy: "u2",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-15"),
    lastContactedDate: new Date("2024-12-15"),
    statusHistory: [
      {
        id: "sh1",
        toStatus: "New",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-01"),
        notes: "Lead created from website inquiry form",
      },
      {
        id: "sh2",
        fromStatus: "New",
        toStatus: "Contacted",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-03"),
        notes: "Initial contact made via email. Positive response received.",
        duration: 2,
      },
      {
        id: "sh3",
        fromStatus: "Contacted",
        toStatus: "Qualified",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-05"),
        notes: "Lead qualified - budget ₹45L approved, Dr. Gupta is decision maker",
        duration: 2,
      },
      {
        id: "sh4",
        fromStatus: "Qualified",
        toStatus: "Visit Scheduled",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-10"),
        notes: "Visit scheduled for Dec 18, 2024 at 10:00 AM",
        duration: 5,
      },
      {
        id: "sh5",
        fromStatus: "Visit Scheduled",
        toStatus: "Visit Completed",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-18"),
        notes: "Visit completed successfully. Demo requested.",
        duration: 8,
      },
      {
        id: "sh6",
        fromStatus: "Visit Completed",
        toStatus: "Demo Scheduled",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-19"),
        notes: "Demo scheduled for Dec 20, 2024",
        duration: 1,
      },
      {
        id: "sh7",
        fromStatus: "Demo Scheduled",
        toStatus: "Quotation Sent",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-21"),
        notes: "Quotation QT-2024-001 sent after successful demo",
        duration: 2,
      },
    ],
  },
  {
    id: "LD-2024-0002",
    firstName: "Meera",
    lastName: "Reddy",
    leadName: "Dr. Meera Reddy",
    email: "meera.reddy@fortis.com",
    phone: "+91 98765 22222",
    companyName: "Fortis Healthcare",
    industry: "Healthcare - Multi-specialty Hospital",
    website: "www.fortishealthcare.com",
    address: "Mulund Goregaon Link Road, Mulund West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400080",
    status: "Visit Completed",
    source: "Trade Show - Medtech Expo 2024",
    leadType: "Hot",
    leadScore: 90,
    preferredContactMethod: "Phone",
    nextFollowUpDate: new Date("2024-12-20"),
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    interestedProducts: ["is4", "is5"],
    employeeCount: "1000-5000",
    annualRevenue: "₹300Cr+",
    notes: "Urgent requirement for cardiology equipment. Budget ₹60L approved. Tender process starting Jan 2025.",
    createdBy: "u5",
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-19"),
    lastContactedDate: new Date("2024-12-19"),
    statusHistory: [
      {
        id: "sh8",
        toStatus: "New",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-05"),
        notes: "Lead captured at Medtech Expo 2024 booth",
      },
      {
        id: "sh9",
        fromStatus: "New",
        toStatus: "Contacted",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-06"),
        notes: "Follow-up call completed. Very interested.",
        duration: 1,
      },
      {
        id: "sh10",
        fromStatus: "Contacted",
        toStatus: "Qualified",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-08"),
        notes: "Budget confirmed. Urgent requirement. HOD approval received.",
        duration: 2,
      },
      {
        id: "sh11",
        fromStatus: "Qualified",
        toStatus: "Visit Scheduled",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-10"),
        notes: "Visit scheduled for Dec 19, 2024",
        duration: 2,
      },
      {
        id: "sh12",
        fromStatus: "Visit Scheduled",
        toStatus: "Visit Completed",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-19"),
        notes: "Visit completed. Detailed requirements discussed. Quotation requested.",
        duration: 9,
      },
    ],
  },
  {
    id: "LD-2024-0003",
    firstName: "Vikram",
    lastName: "Malhotra",
    leadName: "Dr. Vikram Malhotra",
    email: "vikram.malhotra@max.com",
    phone: "+91 98765 33333",
    companyName: "Max Healthcare",
    industry: "Healthcare - Multi-specialty Hospital",
    address: "Press Enclave Road, Saket",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110017",
    status: "Qualified",
    source: "Referral - Dr. Sanjay Gupta",
    leadType: "Warm",
    leadScore: 70,
    preferredContactMethod: "WhatsApp",
    nextFollowUpDate: new Date("2024-12-23"),
    introducerName: "Dr. Sanjay Gupta",
    introducerCompany: "Apollo Hospitals",
    introducerContact: "+91 98765 11111",
    interestedProducts: ["is3", "is1"],
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    employeeCount: "1000-5000",
    notes: "Referred by Dr. Sanjay Gupta from Apollo. Looking for spirometry equipment for pulmonology dept.",
    createdBy: "u2",
    createdAt: new Date("2024-12-14"),
    updatedAt: new Date("2024-12-17"),
    lastContactedDate: new Date("2024-12-17"),
    statusHistory: [
      {
        id: "sh13",
        toStatus: "New",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-14"),
        notes: "Referral lead from Dr. Sanjay Gupta",
      },
      {
        id: "sh14",
        fromStatus: "New",
        toStatus: "Contacted",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-16"),
        notes: "Initial WhatsApp conversation. Positive response.",
        duration: 2,
      },
      {
        id: "sh15",
        fromStatus: "Contacted",
        toStatus: "Qualified",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-17"),
        notes: "Budget discussion completed. Qualified for visit.",
        duration: 1,
      },
    ],
  },
  {
    id: "LD-2024-0004",
    firstName: "Anjali",
    lastName: "Kapoor",
    leadName: "Dr. Anjali Kapoor",
    email: "anjali.kapoor@medanta.org",
    phone: "+91 98765 44444",
    companyName: "Medanta - The Medicity",
    industry: "Healthcare - Super Specialty Hospital",
    website: "www.medanta.org",
    address: "CH Baktawar Singh Road, Sector 38",
    city: "Gurugram",
    state: "Haryana",
    pincode: "122001",
    status: "Converted - PO Received",
    source: "Cold Call",
    leadType: "Hot",
    leadScore: 95,
    preferredContactMethod: "Email",
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    interestedProducts: ["is2", "is1"],
    employeeCount: "5000+",
    annualRevenue: "₹800Cr+",
    notes: "Successfully converted. PO received for ₹42L. Installation scheduled for January 2025.",
    createdBy: "u2",
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-12-10"),
    lastContactedDate: new Date("2024-12-10"),
    statusHistory: [
      {
        id: "sh16",
        toStatus: "New",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-11-15"),
        notes: "Cold call lead - initial interest shown",
      },
      {
        id: "sh17",
        fromStatus: "New",
        toStatus: "Contacted",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-11-18"),
        notes: "Follow-up email sent with product brochures",
        duration: 3,
      },
      {
        id: "sh18",
        fromStatus: "Contacted",
        toStatus: "Qualified",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-11-22"),
        notes: "Budget approved ₹45L. Timeline: Dec 2024",
        duration: 4,
      },
      {
        id: "sh19",
        fromStatus: "Qualified",
        toStatus: "Visit Scheduled",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-11-25"),
        notes: "Visit scheduled for Nov 28",
        duration: 3,
      },
      {
        id: "sh20",
        fromStatus: "Visit Scheduled",
        toStatus: "Visit Completed",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-11-28"),
        notes: "Visit successful. Demo arranged.",
        duration: 3,
      },
      {
        id: "sh21",
        fromStatus: "Visit Completed",
        toStatus: "Demo Scheduled",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-11-30"),
        notes: "Demo scheduled for Dec 2",
        duration: 2,
      },
      {
        id: "sh22",
        fromStatus: "Demo Scheduled",
        toStatus: "Quotation Sent",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-03"),
        notes: "Quotation sent after successful demo",
        duration: 3,
      },
      {
        id: "sh23",
        fromStatus: "Quotation Sent",
        toStatus: "Negotiation",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-05"),
        notes: "Price negotiation in progress",
        duration: 2,
      },
      {
        id: "sh24",
        fromStatus: "Negotiation",
        toStatus: "Converted - PO Received",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-10"),
        notes: "PO received for ₹42L. Final price agreed.",
        duration: 5,
      },
    ],
  },
  {
    id: "LD-2024-0005",
    firstName: "Rohit",
    lastName: "Verma",
    leadName: "Dr. Rohit Verma",
    email: "rohit.verma@manipal.com",
    phone: "+91 98765 55555",
    companyName: "Manipal Hospitals",
    industry: "Healthcare - Multi-specialty Hospital",
    website: "www.manipalhospitals.com",
    address: "98 HAL Airport Road, Kodihalli",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560017",
    status: "Visit Scheduled",
    source: "LinkedIn",
    leadType: "Warm",
    leadScore: 65,
    preferredContactMethod: "Phone",
    nextFollowUpDate: new Date("2024-12-24"),
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    interestedProducts: ["is5", "is4"],
    employeeCount: "1000-5000",
    annualRevenue: "₹250Cr+",
    notes: "Expansion project Q1 2025. Multiple departments interested in equipment upgrade.",
    createdBy: "u5",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-16"),
    lastContactedDate: new Date("2024-12-16"),
    statusHistory: [
      {
        id: "sh25",
        toStatus: "New",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-10"),
        notes: "LinkedIn connection converted to lead",
      },
      {
        id: "sh26",
        fromStatus: "New",
        toStatus: "Contacted",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-12"),
        notes: "Phone call - discussed expansion plans",
        duration: 2,
      },
      {
        id: "sh27",
        fromStatus: "Contacted",
        toStatus: "Qualified",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-14"),
        notes: "Qualified for Q1 2025 project. Budget discussion pending.",
        duration: 2,
      },
      {
        id: "sh28",
        fromStatus: "Qualified",
        toStatus: "Visit Scheduled",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-16"),
        notes: "Visit scheduled for Dec 24, 2024",
        duration: 2,
      },
    ],
  },
  {
    id: "LD-2024-0006",
    firstName: "Neha",
    lastName: "Chatterjee",
    leadName: "Dr. Neha Chatterjee",
    email: "neha.chatterjee@amri.in",
    phone: "+91 98765 66666",
    companyName: "AMRI Hospitals",
    industry: "Healthcare - Multi-specialty Hospital",
    website: "www.amri.in",
    address: "JC-16 & 17, Sector III, Salt Lake City",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700098",
    status: "New",
    source: "Email Campaign",
    leadType: "Cold",
    leadScore: 40,
    preferredContactMethod: "Email",
    assignedTo: "u4",
    assignedToName: "Sneha Reddy",
    interestedProducts: ["is1"],
    notes: "Responded to email campaign. Initial inquiry about pulmonology equipment. Needs follow-up.",
    createdBy: "u4",
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-16"),
    statusHistory: [
      {
        id: "sh29",
        toStatus: "New",
        changedBy: "u4",
        changedByName: "Sneha Reddy",
        timestamp: new Date("2024-12-16"),
        notes: "Lead from email campaign - December 2024",
      },
    ],
  },
]

// Mock Visits
export const mockVisits: Visit[] = [
  {
    id: "18122024-001", // Updated to DDMMYYYY-VISITNUMBER format
    leadId: "LD-2024-0001",
    customerName: "Dr. Sanjay Gupta - Apollo Hospitals",
    pocName: "Dr. Sanjay Gupta",
    pocMobile: "+91 98765 11111",
    pocEmail: "sanjay.gupta@apollo.com",
    department: "Pulmonology",
    visitType: "Initial",
    scheduledDate: new Date("2024-12-18"),
    scheduledTime: "10:00 AM",
    status: "Completed",
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    purpose: "Product demonstration and requirements gathering for FeNO equipment",
    productsToDiscuss: ["is1", "is2"], // Added products to discuss
    address: "Indraprastha Apollo Hospital, Sarita Vihar",
    city: "New Delhi",
    state: "Delhi",
    pincode: "110076",
    outcome: "Meeting successful. Dr. Gupta very interested in NObreath FeNO. Demo requested for Dec 20.",
    outcomeStatus: "Demo Request / Trial Request",
    outcomeRemarks: "Budget approved. Demo to be arranged at earliest. 3 units required.",
    followUpRequired: true,
    followUpDate: new Date("2024-12-20"),
    statusHistory: [
      {
        id: "vsh1",
        toStatus: "Scheduled",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-10"),
        notes: "Initial visit scheduled with Dr. Gupta",
      },
      {
        id: "vsh2",
        fromStatus: "Scheduled",
        toStatus: "Confirmed",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-17"),
        notes: "Visit confirmed by hospital administration",
        duration: 7,
      },
      {
        id: "vsh3",
        fromStatus: "Confirmed",
        toStatus: "Completed",
        changedBy: "u2",
        changedByName: "Priya Sharma",
        timestamp: new Date("2024-12-18"),
        notes: "Visit completed successfully. Demo requested for NObreath FeNO.",
        duration: 1,
      },
    ],
    createdBy: "u2",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-18"),
  },
  {
    id: "19122024-001",
    leadId: "LD-2024-0002",
    customerName: "Dr. Meera Reddy - Fortis Healthcare",
    pocName: "Dr. Meera Reddy",
    pocMobile: "+91 98765 22222",
    pocEmail: "meera.reddy@fortis.com",
    department: "Cardiology",
    visitType: "Initial",
    scheduledDate: new Date("2024-12-19"),
    scheduledTime: "2:30 PM",
    status: "Completed",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    purpose: "Discuss cardiology equipment requirements for new wing",
    productsToDiscuss: ["is4", "is5"],
    address: "Mulund Goregaon Link Road, Mulund West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400080",
    outcome: "Excellent meeting. Discussed CustoCardio BT specifications. Quotation requested.",
    outcomeStatus: "Request Quotation",
    outcomeRemarks: "Urgent requirement. Tender process starts Jan 2025. Need quotation by Dec 22.",
    followUpRequired: true,
    followUpDate: new Date("2024-12-22"),
    statusHistory: [
      {
        id: "vsh4",
        toStatus: "Scheduled",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-10"),
        notes: "Visit scheduled for initial discussion",
      },
      {
        id: "vsh5",
        fromStatus: "Scheduled",
        toStatus: "Confirmed",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-18"),
        notes: "Dr. Reddy confirmed availability",
        duration: 8,
      },
      {
        id: "vsh6",
        fromStatus: "Confirmed",
        toStatus: "Completed",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-19"),
        notes: "Meeting completed. Quotation requested for cardiology equipment.",
        duration: 1,
      },
    ],
    createdBy: "u5",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-19"),
  },
  {
    id: "24122024-001",
    leadId: "LD-2024-0005",
    customerName: "Dr. Rohit Verma - Manipal Hospitals",
    pocName: "Dr. Rohit Verma",
    pocMobile: "+91 98765 55555",
    pocEmail: "rohit.verma@manipal.com",
    department: "Cardiology",
    visitType: "Initial",
    scheduledDate: new Date("2024-12-24"),
    scheduledTime: "11:00 AM",
    status: "Scheduled",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    purpose: "Discuss expansion project equipment requirements",
    productsToDiscuss: ["is4", "is5"],
    address: "98 HAL Airport Road, Kodihalli",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560017",
    followUpRequired: true,
    statusHistory: [
      {
        id: "vsh7",
        toStatus: "Scheduled",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-16"),
        notes: "Visit scheduled for expansion project discussion",
      },
    ],
    createdBy: "u5",
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-16"),
  },
  {
    id: "15122024-001",
    customerName: "Dr. Suresh Nair - Kerala Medical College",
    pocName: "Dr. Suresh Nair",
    pocMobile: "+91 98765 77777",
    pocEmail: "suresh.nair@kmc.edu",
    department: "Pulmonology",
    visitType: "Initial",
    scheduledDate: new Date("2024-12-15"),
    scheduledTime: "3:00 PM",
    status: "Completed",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    purpose: "General inquiry about medical equipment",
    productsToDiscuss: ["is3"],
    address: "Medical College Road",
    city: "Thiruvananthapuram",
    state: "Kerala",
    pincode: "695011",
    outcome: "Good discussion but no immediate requirement. Will contact in Q2 2025.",
    outcomeStatus: "Follow-up",
    outcomeRemarks: "Budget approval pending. Follow-up in March 2025.",
    followUpRequired: true,
    followUpDate: new Date("2025-03-01"),
    statusHistory: [
      {
        id: "vsh8",
        toStatus: "Scheduled",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-08"),
        notes: "Initial visit scheduled",
      },
      {
        id: "vsh9",
        fromStatus: "Scheduled",
        toStatus: "Rescheduled",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-12"),
        notes: "Rescheduled due to Dr. Nair's unavailability. New date: Dec 15",
        duration: 4,
      },
      {
        id: "vsh10",
        fromStatus: "Rescheduled",
        toStatus: "Confirmed",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-14"),
        notes: "Confirmed for new date",
        duration: 2,
      },
      {
        id: "vsh11",
        fromStatus: "Confirmed",
        toStatus: "Completed",
        changedBy: "u5",
        changedByName: "Vikram Singh",
        timestamp: new Date("2024-12-15"),
        notes: "Visit completed. Long-term follow-up scheduled for Q2 2025.",
        duration: 1,
      },
    ],
    rescheduledDate: new Date("2024-12-15"),
    rescheduledReason: "Dr. Nair had emergency surgery scheduled on original date",
    createdBy: "u5",
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-15"),
  },
]

// Mock Enquiries
export const mockEnquiries: Enquiry[] = [
  {
    id: "e1",
    leadId: "LD-2024-0001",
    customerId: "LD-2024-0001",
    visitId: "18122024-001",
    products: [
      {
        productId: "p1",
        productName: "NObreath FeNO",
        quantity: 3,
        unitPrice: 21000,
        discount: 5,
        finalPrice: 59850,
      },
    ],
    status: "Quote Sent",
    priceCategory: "A",
    totalAmount: 59850,
    notes: "Enquiry after successful visit and demo. 3 units for different departments.",
    createdBy: "u2",
    createdByName: "Priya Sharma",
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-21"),
  },
  {
    id: "e2",
    leadId: "LD-2024-0002",
    customerId: "LD-2024-0002",
    visitId: "19122024-001",
    products: [
      {
        productId: "p3",
        productName: "CustoCardio BT",
        quantity: 2,
        unitPrice: 21000,
        discount: 3,
        finalPrice: 40740,
      },
    ],
    status: "Under Review",
    priceCategory: "A",
    totalAmount: 40740,
    notes: "Urgent requirement. Quotation requested after visit.",
    createdBy: "u5",
    createdByName: "Vikram Singh",
    createdAt: new Date("2024-12-19"),
    updatedAt: new Date("2024-12-20"),
  },
]

// Mock Quotations
export const mockQuotations: Quotation[] = [
  {
    id: "q1",
    enquiryId: "e1",
    quoteNumber: "QT-2024-001",
    customerId: "LD-2024-0001",
    customerName: "Dr. Sanjay Gupta - Apollo Hospitals",
    products: [
      {
        productId: "p1",
        productName: "NObreath FeNO",
        manufacturer: "Bedfont Scientific",
        quantity: 3,
        unitPrice: 21000,
        discount: 5,
        tax: 18,
        finalPrice: 70623,
      },
    ],
    subtotal: 63000,
    discount: 3150,
    tax: 10773,
    totalAmount: 70623,
    status: "Sent to Customer",
    validUntil: new Date("2025-01-21"),
    terms:
      "Payment: 50% advance, 50% on delivery. Delivery: 15 days. Warranty: 1 year. Installation & training included.",
    notes: "Special pricing approved for bulk order of 3 units.",
    createdBy: "u2",
    createdByName: "Priya Sharma",
    approvedBy: "u1",
    approvedByName: "Rajesh Kumar",
    approvalDate: new Date("2024-12-21"),
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-21"),
  },
  {
    id: "q2",
    enquiryId: "e2",
    quoteNumber: "QT-2024-002",
    customerId: "LD-2024-0002",
    customerName: "Dr. Meera Reddy - Fortis Healthcare",
    products: [
      {
        productId: "p3",
        productName: "CustoCardio BT",
        manufacturer: "Customed",
        quantity: 2,
        unitPrice: 21000,
        discount: 3,
        tax: 18,
        finalPrice: 48048,
      },
    ],
    subtotal: 42000,
    discount: 1260,
    tax: 7308,
    totalAmount: 48048,
    status: "Pending Approval",
    validUntil: new Date("2025-01-22"),
    terms: "Payment: 40% advance, 60% on delivery. Delivery: 10 days. Warranty: 2 years. AMC available.",
    notes: "Urgent requirement for tender submission.",
    createdBy: "u5",
    createdByName: "Vikram Singh",
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-20"),
  },
]

// Mock Demos
export const mockDemos: Demo[] = [
  {
    id: "d1",
    quotationId: "q1",
    customerId: "LD-2024-0001",
    customerName: "Dr. Sanjay Gupta - Apollo Hospitals",
    products: ["NObreath FeNO"],
    scheduledDate: new Date("2024-12-20"),
    scheduledTime: "2:00 PM",
    location: "Pulmonology Department, Apollo Hospitals, New Delhi",
    status: "Completed",
    assignedTo: "u6",
    assignedToName: "Kavita Desai",
    outcome: "Demo extremely successful. All 3 HODs attended. Impressed with accuracy and ease of use.",
    feedback: "Positive feedback from all stakeholders. Ready to proceed with purchase. Requested quotation.",
    createdAt: new Date("2024-12-18"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "d2",
    quotationId: "q2",
    customerId: "LD-2024-0002",
    customerName: "Dr. Meera Reddy - Fortis Healthcare",
    products: ["CustoCardio BT"],
    scheduledDate: new Date("2024-12-23"),
    scheduledTime: "11:00 AM",
    location: "Cardiology Department, Fortis Mulund, Mumbai",
    status: "Scheduled",
    assignedTo: "u6",
    assignedToName: "Kavita Desai",
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-20"),
  },
]

// Mock Service Requests
export const mockServiceRequests: ServiceRequest[] = [
  {
    id: "s1",
    ticketNumber: "SRV-2024-001",
    customerId: "LD-2024-0004",
    customerName: "Medanta - The Medicity",
    productId: "p2",
    productName: "SmartPFT USB",
    issueType: "Installation",
    priority: "High",
    description: "Installation of newly purchased SmartPFT USB unit. Customer ready for installation.",
    status: "Scheduled",
    assignedTo: "u3",
    assignedToName: "Amit Patel",
    scheduledDate: new Date("2025-01-05"),
    createdAt: new Date("2024-12-12"),
    updatedAt: new Date("2024-12-14"),
  },
  {
    id: "s2",
    ticketNumber: "SRV-2024-002",
    customerId: "LD-2024-0001",
    customerName: "Apollo Hospitals",
    productId: "p2",
    productName: "SmartPFT USB",
    issueType: "Calibration",
    priority: "Medium",
    description: "Annual calibration required for existing SmartPFT unit in Pulmonology dept.",
    status: "Scheduled",
    assignedTo: "u3",
    assignedToName: "Amit Patel",
    scheduledDate: new Date("2024-12-26"),
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-15"),
  },
  {
    id: "s3",
    ticketNumber: "SRV-2024-003",
    customerId: "LD-2024-0002",
    customerName: "Fortis Healthcare",
    productId: "p4",
    productName: "CustoCardio",
    issueType: "Repair",
    priority: "Urgent",
    description: "USB port not working on existing ECG machine. Requires immediate attention.",
    status: "In Progress",
    assignedTo: "u3",
    assignedToName: "Amit Patel",
    scheduledDate: new Date("2024-12-17"),
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-17"),
  },
]

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: "c1",
    name: "Apollo Hospitals",
    industry: "Healthcare",
    website: "www.apollohospitals.com",
    city: "New Delhi",
    state: "Delhi",
    phone: "+91 11 2692 5858",
    email: "info@apollo.com",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "c1a",
    name: "Apollo Hospitals - Mumbai Branch",
    parentCompanyId: "c1",
    industry: "Healthcare",
    city: "Mumbai",
    state: "Maharashtra",
    phone: "+91 22 6767 8900",
    email: "mumbai@apollo.com",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "c2",
    name: "Fortis Healthcare",
    industry: "Healthcare",
    website: "www.fortishealthcare.com",
    city: "Mumbai",
    state: "Maharashtra",
    phone: "+91 22 6754 3000",
    email: "info@fortis.com",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "c3",
    name: "Max Healthcare",
    industry: "Healthcare",
    website: "www.maxhealthcare.in",
    city: "Bangalore",
    state: "Karnataka",
    phone: "+91 80 4140 4140",
    email: "info@max.com",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "c3a",
    name: "Max Healthcare - Delhi Branch",
    parentCompanyId: "c3",
    industry: "Healthcare",
    city: "New Delhi",
    state: "Delhi",
    phone: "+91 11 6629 6000",
    email: "delhi@max.com",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "c4",
    name: "Medanta",
    industry: "Healthcare",
    website: "www.medanta.org",
    city: "Gurugram",
    state: "Haryana",
    phone: "+91 124 414 1414",
    email: "info@medanta.org",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "c5",
    name: "Manipal Hospitals",
    industry: "Healthcare",
    website: "www.manipalhospitals.com",
    city: "Bangalore",
    state: "Karnataka",
    phone: "+91 80 2502 4444",
    email: "info@manipal.com",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: "a1",
    entityType: "Lead",
    entityId: "LD-2024-0001",
    action: "Created",
    description: "New lead created from website inquiry",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-01"),
  },
  {
    id: "a2",
    entityType: "Lead",
    entityId: "LD-2024-0001",
    action: "Status Changed",
    description: "Status changed from New to Contacted",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-03"),
  },
  {
    id: "a3",
    entityType: "Visit",
    entityId: "18122024-001",
    action: "Scheduled",
    description: "Initial visit scheduled for Apollo Hospitals",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-10"),
  },
  {
    id: "a4",
    entityType: "Visit",
    entityId: "18122024-001",
    action: "Completed",
    description: "Visit completed successfully. Demo requested.",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-18"),
  },
  {
    id: "a5",
    entityType: "Demo",
    entityId: "d1",
    action: "Scheduled",
    description: "Product demo scheduled for NObreath FeNO",
    userId: "u6",
    userName: "Kavita Desai",
    timestamp: new Date("2024-12-18"),
  },
  {
    id: "a6",
    entityType: "Demo",
    entityId: "d1",
    action: "Completed",
    description: "Demo completed successfully with positive feedback",
    userId: "u6",
    userName: "Kavita Desai",
    timestamp: new Date("2024-12-20"),
  },
  {
    id: "a7",
    entityType: "Enquiry",
    entityId: "e1",
    action: "Created",
    description: "Enquiry created for NObreath FeNO x3",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-20"),
  },
  {
    id: "a8",
    entityType: "Quotation",
    entityId: "q1",
    action: "Created",
    description: "Quotation QT-2024-001 created",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-20"),
  },
  {
    id: "a9",
    entityType: "Quotation",
    entityId: "q1",
    action: "Approved",
    description: "Quotation approved by Sales Manager",
    userId: "u1",
    userName: "Rajesh Kumar",
    timestamp: new Date("2024-12-21"),
  },
  {
    id: "a10",
    entityType: "Quotation",
    entityId: "q1",
    action: "Sent",
    description: "Quotation sent to customer via email",
    userId: "u2",
    userName: "Priya Sharma",
    timestamp: new Date("2024-12-21"),
  },
  {
    id: "a11",
    entityType: "Service",
    entityId: "s3",
    action: "Created",
    description: "Service request created for USB repair",
    userId: "u3",
    userName: "Amit Patel",
    timestamp: new Date("2024-12-16"),
  },
  {
    id: "a12",
    entityType: "Lead",
    entityId: "LD-2024-0002",
    action: "Created",
    description: "Lead captured at Medtech Expo 2024",
    userId: "u5",
    userName: "Vikram Singh",
    timestamp: new Date("2024-12-05"),
  },
]

// Mock Items/Services
export const mockItemsServices: ItemService[] = [
  {
    id: "is1",
    name: "Pulmonology Equipment",
    category: "Product",
    description: "General pulmonology equipment and devices",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is2",
    name: "FeNO Analyzer",
    category: "Product",
    description: "Fractional exhaled Nitric Oxide analyzer",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is3",
    name: "Spirometer",
    category: "Product",
    description: "Lung function testing equipment",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is4",
    name: "Cardiology Equipment",
    category: "Product",
    description: "General cardiology equipment and devices",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is5",
    name: "ECG Machine",
    category: "Product",
    description: "Electrocardiogram machines",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is6",
    name: "Installation Service",
    category: "Service",
    description: "Professional installation and setup of equipment",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is7",
    name: "Training Service",
    category: "Service",
    description: "Staff training for equipment operation",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is8",
    name: "AMC Service",
    category: "Service",
    description: "Annual Maintenance Contract",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "is9",
    name: "Calibration Service",
    category: "Service",
    description: "Equipment calibration and verification",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Follow-up on Quotation QT-2024-001",
    description: "Call Dr. Sanjay Gupta to discuss quotation and answer any questions. Check if PO is ready.",
    entityType: "Quotation",
    entityId: "q1",
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    priority: "High",
    status: "Open",
    dueDate: new Date("2024-12-22"),
    createdBy: "u1",
    createdAt: new Date("2024-12-21"),
    updatedAt: new Date("2024-12-21"),
  },
  {
    id: "t2",
    title: "Prepare and send Quotation for Fortis Healthcare",
    description:
      "Create quotation for Dr. Meera Reddy based on visit discussion. Get manager approval and send by Dec 22.",
    entityType: "Lead",
    entityId: "LD-2024-0002",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    priority: "Urgent",
    status: "In Progress",
    dueDate: new Date("2024-12-22"),
    createdBy: "u5",
    createdAt: new Date("2024-12-19"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "t3",
    title: "Schedule Visit for Max Healthcare",
    description: "Contact Dr. Vikram Malhotra to schedule visit for the week of Dec 23-27.",
    entityType: "Lead",
    entityId: "LD-2024-0003",
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    priority: "Medium",
    status: "Open",
    dueDate: new Date("2024-12-23"),
    createdBy: "u2",
    createdAt: new Date("2024-12-17"),
    updatedAt: new Date("2024-12-17"),
  },
  {
    id: "t4",
    title: "Prepare Demo Equipment for Fortis",
    description: "Prepare CustoCardio BT demo unit and ensure all accessories are ready for Dec 23 demo.",
    entityType: "Demo",
    entityId: "d2",
    assignedTo: "u6",
    assignedToName: "Kavita Desai",
    priority: "High",
    status: "In Progress",
    dueDate: new Date("2024-12-23"),
    createdBy: "u5",
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-21"),
  },
  {
    id: "t5",
    title: "Complete Service Request SRV-2024-003",
    description: "Repair USB port on CustoCardio unit at Fortis. Parts ordered, installation pending.",
    entityType: "Service",
    entityId: "s3",
    assignedTo: "u3",
    assignedToName: "Amit Patel",
    priority: "Urgent",
    status: "In Progress",
    dueDate: new Date("2024-12-18"),
    createdBy: "u3",
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-17"),
  },
  {
    id: "t6",
    title: "Schedule Installation at Medanta",
    description: "Coordinate with Medanta for SmartPFT USB installation on Jan 5. Confirm technician availability.",
    entityType: "Service",
    entityId: "s1",
    assignedTo: "u3",
    assignedToName: "Amit Patel",
    priority: "Medium",
    status: "Open",
    dueDate: new Date("2024-12-28"),
    createdBy: "u3",
    createdAt: new Date("2024-12-14"),
    updatedAt: new Date("2024-12-14"),
  },
  {
    id: "t7",
    title: "Send Product Brochures to AMRI Hospitals",
    description: "Follow-up with Dr. Neha Chatterjee. Send detailed brochures and pricing for pulmonology equipment.",
    entityType: "Lead",
    entityId: "LD-2024-0006",
    assignedTo: "u4",
    assignedToName: "Sneha Reddy",
    priority: "Low",
    status: "Open",
    dueDate: new Date("2024-12-18"),
    createdBy: "u4",
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-16"),
  },
  {
    id: "t8",
    title: "Prepare for Manipal Visit on Dec 24",
    description: "Review expansion project requirements and prepare presentation for Dr. Rohit Verma meeting.",
    entityType: "Visit",
    entityId: "24122024-001",
    assignedTo: "u5",
    assignedToName: "Vikram Singh",
    priority: "High",
    status: "Open",
    dueDate: new Date("2024-12-24"),
    createdBy: "u5",
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-16"),
  },
  {
    id: "t9",
    title: "Request PO from Apollo Hospitals",
    description: "Follow-up with Dr. Sanjay Gupta on quotation QT-2024-001. Request confirmation and PO issuance.",
    entityType: "Quotation",
    entityId: "q1",
    assignedTo: "u2",
    assignedToName: "Priya Sharma",
    priority: "High",
    status: "Open",
    dueDate: new Date("2024-12-23"),
    createdBy: "u2",
    createdAt: new Date("2024-12-21"),
    updatedAt: new Date("2024-12-21"),
  },
  {
    id: "t10",
    title: "Schedule Calibration at Apollo",
    description: "Confirm Dec 26 calibration appointment for SmartPFT USB at Apollo Pulmonology dept.",
    entityType: "Service",
    entityId: "s2",
    assignedTo: "u3",
    assignedToName: "Amit Patel",
    priority: "Medium",
    status: "Open",
    dueDate: new Date("2024-12-25"),
    createdBy: "u3",
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-15"),
  },
]

export const mockTenants: Tenant[] = [
  {
    id: "tenant-1",
    name: "Apollo Hospitals Enterprise",
    domain: "apollo.nexflow.com",
    status: "Active",
    plan: "Enterprise",
    maxUsers: 500,
    currentUsers: 342,
    adminName: "Dr. Prathap C. Reddy",
    adminEmail: "admin@apollohospitals.com",
    adminPhone: "+91 44 2829 3333",
    companyAddress: "19, Bishop Gardens",
    companyCity: "Chennai",
    companyState: "Tamil Nadu",
    companyCountry: "India",
    companyPincode: "600086",
    features: ["advanced-analytics", "custom-workflows", "api-access", "white-labeling", "priority-support"],
    customBranding: {
      logo: "/logos/apollo.png",
      primaryColor: "#0066CC",
      secondaryColor: "#FFB600",
    },
    billingEmail: "billing@apollohospitals.com",
    subscriptionStartDate: new Date("2024-01-01"),
    subscriptionEndDate: new Date("2025-12-31"),
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-15"),
    createdBy: "platform-admin",
    lastLoginDate: new Date("2024-12-21"),
    notes: "Premium enterprise customer. Full deployment across 70+ hospitals.",
  },
  {
    id: "tenant-2",
    name: "Fortis Healthcare Limited",
    domain: "fortis.nexflow.com",
    status: "Active",
    plan: "Enterprise",
    maxUsers: 300,
    currentUsers: 245,
    adminName: "Dr. Ashutosh Raghuvanshi",
    adminEmail: "admin@fortishealthcare.com",
    adminPhone: "+91 124 496 2200",
    companyAddress: "Fortis Memorial Research Institute, Sector 44",
    companyCity: "Gurugram",
    companyState: "Haryana",
    companyCountry: "India",
    companyPincode: "122002",
    features: ["advanced-analytics", "custom-workflows", "api-access", "priority-support"],
    customBranding: {
      logo: "/logos/fortis.png",
      primaryColor: "#E31E24",
      secondaryColor: "#FFA500",
    },
    billingEmail: "billing@fortishealthcare.com",
    subscriptionStartDate: new Date("2024-02-01"),
    subscriptionEndDate: new Date("2025-01-31"),
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-10"),
    createdBy: "platform-admin",
    lastLoginDate: new Date("2024-12-20"),
    notes: "Enterprise customer with 45+ hospitals. Annual contract renewal due Jan 2025.",
  },
  {
    id: "tenant-3",
    name: "Max Healthcare",
    domain: "max.nexflow.com",
    status: "Active",
    plan: "Professional",
    maxUsers: 150,
    currentUsers: 98,
    adminName: "Dr. Sandeep Budhiraja",
    adminEmail: "admin@maxhealthcare.com",
    adminPhone: "+91 11 6629 6000",
    companyAddress: "Press Enclave Road, Saket",
    companyCity: "New Delhi",
    companyState: "Delhi",
    companyCountry: "India",
    companyPincode: "110017",
    features: ["advanced-analytics", "custom-workflows", "priority-support"],
    customBranding: {
      logo: "/logos/max.png",
      primaryColor: "#00A551",
      secondaryColor: "#005A2B",
    },
    billingEmail: "billing@maxhealthcare.com",
    subscriptionStartDate: new Date("2024-03-15"),
    subscriptionEndDate: new Date("2025-03-14"),
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-11-20"),
    createdBy: "platform-admin",
    lastLoginDate: new Date("2024-12-19"),
    notes: "Professional plan. 17 hospitals. Considering upgrade to Enterprise for Q2 2025.",
  },
  {
    id: "tenant-4",
    name: "Medanta - The Medicity",
    domain: "medanta.nexflow.com",
    status: "Active",
    plan: "Professional",
    maxUsers: 200,
    currentUsers: 156,
    adminName: "Dr. Naresh Trehan",
    adminEmail: "admin@medanta.org",
    adminPhone: "+91 124 414 1414",
    companyAddress: "CH Baktawar Singh Road, Sector 38",
    companyCity: "Gurugram",
    companyState: "Haryana",
    companyCountry: "India",
    companyPincode: "122001",
    features: ["advanced-analytics", "custom-workflows", "priority-support"],
    customBranding: {
      logo: "/logos/medanta.png",
      primaryColor: "#005EB8",
      secondaryColor: "#FF6B35",
    },
    billingEmail: "billing@medanta.org",
    subscriptionStartDate: new Date("2024-05-01"),
    subscriptionEndDate: new Date("2025-04-30"),
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-12-01"),
    createdBy: "platform-admin",
    lastLoginDate: new Date("2024-12-21"),
    notes: "Super specialty hospital. High engagement. Excellent reference customer.",
  },
  {
    id: "tenant-5",
    name: "Manipal Hospitals",
    domain: "manipal.nexflow.com",
    status: "Active",
    plan: "Enterprise",
    maxUsers: 400,
    currentUsers: 287,
    adminName: "Dr. H. Sudarshan Ballal",
    adminEmail: "admin@manipalhospitals.com",
    adminPhone: "+91 80 2502 4444",
    companyAddress: "98 HAL Airport Road",
    companyCity: "Bangalore",
    companyState: "Karnataka",
    companyCountry: "India",
    companyPincode: "560017",
    features: ["advanced-analytics", "custom-workflows", "api-access", "white-labeling", "priority-support"],
    customBranding: {
      logo: "/logos/manipal.png",
      primaryColor: "#D91E27",
      secondaryColor: "#1D428A",
    },
    billingEmail: "billing@manipalhospitals.com",
    subscriptionStartDate: new Date("2024-06-01"),
    subscriptionEndDate: new Date("2026-05-31"),
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-12-05"),
    createdBy: "platform-admin",
    lastLoginDate: new Date("2024-12-18"),
    notes: "2-year contract. 28 hospitals across India. Expansion planned for 2025.",
  },
]
